[package]
name = "oscilloscope"
version = "0.1.0"
authors = ["nnmm <nnmmgit@gmail.com>"]

[[bin]]
name = "rs-osc"
path = "src/main.rs"

[dependencies]
piston_window = "0.64.0"
jack = "0.5.0"
chan-signal = "0.2.0"
chan = "0.1.19"
