[package]
name = "osc"
version = "0.1.0"
authors = ["nnmm <nnmmgit@gmail.com>"]

[[bin]]
name = "rscope"
path = "src/main.rs"

[dependencies]
chan = "0.1.19"
chan-signal = "0.2.0"
getopts = "0.2"
jack = "0.5.0"
pistoncore-input = "0.17.1"
piston_window = "0.64.0"
